spring:
  application:
    name: api-gateway 

zuul:
  prefix: /api
  routes:
    hashdehash: 
      path: /hashdehash/**
      serviceId: hashdehash-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

server:
    port: 8765
    ssl:
      key-store: /Users/mk/projects/projectX/docker/zuul/keystore.p12
      key-store-password: 12345
      keyStoreType: PKCS12
      keyAlias: tomcat
#server:
#  ssl:
#    key-store: /Users/mk/projects/projectX/docker/zuul/keystore.p12
#    key-store-password: 12345
#    keyStoreType: PKCS12
#    keyAlias: tomcat
     