version: '3'
services:
    hashdehash:
        build:
            context: service/.
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "20k"
                max-file: "5"
        depends_on:
            - discovery-server

    discovery-server:
        build:
            context: eureka/.
        ports:
            - 8761
        restart: on-failure
        
    api-gateway:
        build:
            context: zuul/.
        ports:
            - 8765:8765
        depends_on:
            - discovery-server
        restart: on-failure