version: '3'
services:
    hashdehash:
        build:
            context: .
        restart: on-failure
        ports:
            - 5000:5000
        logging:
            driver: "json-file"
            options:
                max-size: "20k"
                max-file: "5"